### ISSUE TITLE
Doesn't work when used in a UIBarButtonItem as a custom view on a UINavigationBar

### ISSUE THREAD

**Issue by nathanmbrown** [ejvaughan/EVCircularProgressView#4]
I'm seeing the progress view painting up in the top left corner of the navigation bar (0,0) no matter whether it's set as the right or left button item.
![](http://i.gyazo.com/e8fb3a2e38a781f825032b0d3053384b.png)
Is there a way to get this to work? I've tried embedding the progress view in a UIView too but to no avail.

**Comment by Nedskib** [comment]
I've just realised it was actually an error on my part, sorry.
